POST http://localhost:3000/admin/productAdd
Content-Type: application/json

{
    "image": "오지게 맛있는 젤리 이미지2",
    "name": "오지게 맛있는 젤리2",
    "info": "이것은 오지게 맛있는 젤리2",
    "price": 2500
}

###
GET http://localhost:3000/admin/adminprofile

###
GET http://localhost:3000/admin/adminProduct

###
PUT http://localhost:3000/admin/productEdit/1
Content-Type: application/json

{
    "image": "졸라 오지게 맛있는 젤리 이미지",
    "name": "졸라 오지게 맛있는 젤리",
    "info": "이것은 졸라 오지게 맛있는 젤리",
    "price": 2000
}

###
DELETE http://localhost:3000/admin/productDelete/4