GET http://localhost:3000/

###
GET http://localhost:3000/profile

###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "hoon1@naver.com",
    "password": "1234",
    "phone": "010-9999-9999",
    "userType": 1
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "hoon3@naver.com",
    "password": "1234"
}

###
GET http://localhost:3000/auth/logout


###
POST http://localhost:3000/auth/withdrawal
Content-Type: application/json

{
    "password": "1234",
    "passwordConfirm": "1234"
}