GET http://localhost:3000/

###
POST http://localhost:3000/general/cart/2
// 장바구니에 담기

###
GET http://localhost:3000/general/cart/
// 장바구니 조회

###
PATCH http://localhost:3000/general/cart/2
Content-Type: application/json

{
    "modQuantity": 5
}

###
DELETE  http://localhost:3000/general/cart/2
// 장바구니에서 상품 삭제

###
DELETE  http://localhost:3000/general/cart
// 장바구니에서 상품 모두 삭제